### ISSUE TITLE
Complete implementation of Profile section

### ISSUE THREAD

**Issue by BraxWong** [BraxWong/Bitskin-CLI#2]
### Subject of the issue
The Account section of the Bitskins' API has four parts. Profile is the first part, complete implementation and move on to the Affiliate section.
#### Tasks
- [x] Get current session
- [x] Get current balance
- [ ] Update account
- [ ] Update trade link
- [ ] Block my account
